// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package microlink

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LinkServiceClient is the client API for LinkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinkServiceClient interface {
	ShortenLink(ctx context.Context, in *ModifyLinkRequest, opts ...grpc.CallOption) (*ModifyLinkResponse, error)
	LengthenLink(ctx context.Context, in *ModifyLinkRequest, opts ...grpc.CallOption) (*ModifyLinkResponse, error)
	UnShortenLink(ctx context.Context, in *ModifyLinkRequest, opts ...grpc.CallOption) (*ModifyLinkResponse, error)
	UnLengthenLink(ctx context.Context, in *ModifyLinkRequest, opts ...grpc.CallOption) (*ModifyLinkResponse, error)
}

type linkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLinkServiceClient(cc grpc.ClientConnInterface) LinkServiceClient {
	return &linkServiceClient{cc}
}

func (c *linkServiceClient) ShortenLink(ctx context.Context, in *ModifyLinkRequest, opts ...grpc.CallOption) (*ModifyLinkResponse, error) {
	out := new(ModifyLinkResponse)
	err := c.cc.Invoke(ctx, "/microlink.LinkService/ShortenLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkServiceClient) LengthenLink(ctx context.Context, in *ModifyLinkRequest, opts ...grpc.CallOption) (*ModifyLinkResponse, error) {
	out := new(ModifyLinkResponse)
	err := c.cc.Invoke(ctx, "/microlink.LinkService/LengthenLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkServiceClient) UnShortenLink(ctx context.Context, in *ModifyLinkRequest, opts ...grpc.CallOption) (*ModifyLinkResponse, error) {
	out := new(ModifyLinkResponse)
	err := c.cc.Invoke(ctx, "/microlink.LinkService/UnShortenLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkServiceClient) UnLengthenLink(ctx context.Context, in *ModifyLinkRequest, opts ...grpc.CallOption) (*ModifyLinkResponse, error) {
	out := new(ModifyLinkResponse)
	err := c.cc.Invoke(ctx, "/microlink.LinkService/UnLengthenLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkServiceServer is the server API for LinkService service.
// All implementations must embed UnimplementedLinkServiceServer
// for forward compatibility
type LinkServiceServer interface {
	ShortenLink(context.Context, *ModifyLinkRequest) (*ModifyLinkResponse, error)
	LengthenLink(context.Context, *ModifyLinkRequest) (*ModifyLinkResponse, error)
	UnShortenLink(context.Context, *ModifyLinkRequest) (*ModifyLinkResponse, error)
	UnLengthenLink(context.Context, *ModifyLinkRequest) (*ModifyLinkResponse, error)
	mustEmbedUnimplementedLinkServiceServer()
}

// UnimplementedLinkServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLinkServiceServer struct {
}

func (UnimplementedLinkServiceServer) ShortenLink(context.Context, *ModifyLinkRequest) (*ModifyLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShortenLink not implemented")
}
func (UnimplementedLinkServiceServer) LengthenLink(context.Context, *ModifyLinkRequest) (*ModifyLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LengthenLink not implemented")
}
func (UnimplementedLinkServiceServer) UnShortenLink(context.Context, *ModifyLinkRequest) (*ModifyLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnShortenLink not implemented")
}
func (UnimplementedLinkServiceServer) UnLengthenLink(context.Context, *ModifyLinkRequest) (*ModifyLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnLengthenLink not implemented")
}
func (UnimplementedLinkServiceServer) mustEmbedUnimplementedLinkServiceServer() {}

// UnsafeLinkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinkServiceServer will
// result in compilation errors.
type UnsafeLinkServiceServer interface {
	mustEmbedUnimplementedLinkServiceServer()
}

func RegisterLinkServiceServer(s grpc.ServiceRegistrar, srv LinkServiceServer) {
	s.RegisterService(&LinkService_ServiceDesc, srv)
}

func _LinkService_ShortenLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).ShortenLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microlink.LinkService/ShortenLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).ShortenLink(ctx, req.(*ModifyLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkService_LengthenLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).LengthenLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microlink.LinkService/LengthenLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).LengthenLink(ctx, req.(*ModifyLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkService_UnShortenLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).UnShortenLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microlink.LinkService/UnShortenLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).UnShortenLink(ctx, req.(*ModifyLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkService_UnLengthenLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).UnLengthenLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microlink.LinkService/UnLengthenLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).UnLengthenLink(ctx, req.(*ModifyLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LinkService_ServiceDesc is the grpc.ServiceDesc for LinkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LinkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "microlink.LinkService",
	HandlerType: (*LinkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShortenLink",
			Handler:    _LinkService_ShortenLink_Handler,
		},
		{
			MethodName: "LengthenLink",
			Handler:    _LinkService_LengthenLink_Handler,
		},
		{
			MethodName: "UnShortenLink",
			Handler:    _LinkService_UnShortenLink_Handler,
		},
		{
			MethodName: "UnLengthenLink",
			Handler:    _LinkService_UnLengthenLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "link.proto",
}
